### ISSUE TITLE
使用回顾

### ISSUE THREAD

**Issue by 0x3st** [youchen-0/cfblog-pro#1]
虽然我不知道这大致的原理，我只是个小白，但是如果简单复制粘贴就会有好多错误，比如49行的

**Comment by youchen-0** [comment]
抱歉,第四十九行引号位置错了
另外还有一处更新没做完,留下一个bug
马上改
您还发现什么报错吗?

**Comment by 0x3st** [comment]
额，错误的话可以直接复制粘贴到cloudflare的worker里面，在保存的时候会有错误提示，标黄的都是，我不是很懂很抱歉不能详细说明。

**Comment by 0x3st** [comment]
创建文章在首页点击进入会有1101错误
[我的测试页面](http://dev.0x3st.ml/)

**Comment by youchen-0** [comment]
这是cfblog-plus留下的坑,我不会修
暂时看我文章解决[](https://blog.youchen.cf/article/000004/index.html)

**Comment by youchen-0** [comment]
我其实也就勉强能看懂Arronlong大佬写的码,水平有限

**Comment by 0x3st** [comment]
> 这是cfblog-plus留下的坑,我不会修
> 暂时看我文章解决[链接](https://blog.youchen.cf/article/000004/index.html)

确实解决了
fanks!

**Comment by youchen-0** [comment]
有问题欢迎及时提出哈
